import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f5f5f5' },
    content: { padding: 16 },
    title: { fontSize: 24, fontWeight: 'bold', textAlign: 'center', marginBottom: 20, color: '#333' },
    input: { marginBottom: 15 },
    button: { marginTop: 20, paddingVertical: 8 },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f5f5f5' },
    loadingText: { marginTop: 10, fontSize: 16, color: '#555' },
    card: { marginBottom: 20, backgroundColor: '#fff' },
    resultLabel: { fontSize: 18, color: '#333' },
    resultValue: { fontSize: 32, fontWeight: 'bold', color: '#6200ee', marginBottom: 20 },
    detailLabel: { fontSize: 16, color: '#555' },
    detailValue: { fontSize: 18, fontWeight: '500', marginBottom: 10 },
    chartTitle: { fontSize: 20, fontWeight: 'bold', textAlign: 'center', marginTop: 20, color: '#333' },
    chartContainer: { marginTop: 20, padding: 10, backgroundColor: '#ffffff', borderRadius: 10 },
    header: {
    backgroundColor: '#fff',
    ...Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 2 },
        android: { elevation: 4 },
}),
},
    investmentCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
},
    cardTitle: { fontSize: 20, fontWeight: 'bold', color: '#6200ee', marginBottom: 16 },
    cardRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12 },
    cardLabel: { fontSize: 16, color: '#333' },
    cardValue: { fontSize: 16, fontWeight: 'bold' },
    riskTag: { paddingVertical: 4, paddingHorizontal: 10, borderRadius: 12, fontWeight: 'bold', fontSize: 14 },
    riskLow: { color: '#1b5e20', backgroundColor: '#e8f5e9' },
    placeholderContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20, backgroundColor: '#f5f5f5' },
    placeholderIcon: { fontSize: 50, color: '#999', marginBottom: 10 },
    placeholderText: { fontSize: 18, color: '#777', textAlign: 'center' },
});